# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
  push:
    paths-ignore:
    - '**.html'

## todo: ignore generated html files

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate HTML documents
    steps:
      - uses: actions/checkout@v1

      # Setup ldap2html
      - uses: actions/checkout@v1
        with:
          repository: nonylene/ldap2html
          ref: refs/heads/master
          path: ldap2html
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip3 install pipenv
      - run: pipenv install
        working-directory: ../ldap2html

      # Setup OpenLDAP
      - name: Run OpenLDAP background
        run: docker run -p 389:389 -p 636:636 -v ${GITHUB_WORKSPACE}:/repo -v ${GITHUB_WORKSPACE}/../ldap2html/schema:/container/service/slapd/assets/config/bootstrap/ldif/custom --rm --env LDAP_DOMAIN="ku-ldif.github.io" -d --name ldap osixia/openldap --copy-service
      - run: sleep 10 # Wait until openldap boot

      - name: Add ldap entries
        run: |
          for f in src/*.html.ldif; do
            docker exec ldap ldapadd -x -H ldap://localhost -D "cn=admin,dc=ku-ldif,dc=github,dc=io" -w admin  -f /repo/$f
          done
      - name: Generate html files
        run: pipenv run python3 main.py -H ldap://localhost -b 'dc=ku-ldif,dc=github,dc=io' -D 'cn=admin,dc=ku-ldif,dc=github,dc=io' -w admin -v
        working-directory: ../ldap2html
      - run: docker stop ldap

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: out
          path: ../ldap2html/out

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [generate]
    name: Deploy (Update repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup git
        run: |
          git config --local user.email "ku-ldif@users.noreply.github.com"
          git config --local user.name "ku-ldif"

      - uses: actions/download-artifact@v1
        with:
          name: out
      - run: git status
      - run: echo ${{ github.ref }}
      - run: ls out
      - run: ls out/*
      - run: |
          mv out/*.html ./
          rm -r out
      - run: git diff

      - name: Git commit and push if diff exists
        run: |
          git add *.html
          if ! git diff --staged --quiet; then
            git commit -m "Generate HTML documents"
            git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/ku-ldif/ku-ldif.github.io.git HEAD:master
          fi
